
name: 'snowplow_bq'
version: '1.0'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
    snowplow_bq:
        base:
            materialized: ephemeral

        vars:
            "snowplow:context:web_page": null
            "snowplow:context:submit_form:elements": null
            "snowplow:context:submit_form": null
            "snowplow:context:submit_form:classes": null
            "snowplow:event_daily": null
            "snowplow:event_all": null
